from typing import Any

from dotenv import load_dotenv
from google import genai
from google.genai import types

from app.planner.interface import QueryPlanner
from app.registry.operations import OperationRegistry
from app.schemas.query import QueryPlan

load_dotenv()

PLANNER_SYSTEM_PROMPT = """
You are the planning engine for SatQuery-AI.

Your job is to convert a user's natural-language geospatial query
into a structured QueryPlan.

Rules:

1. Only produce a QueryPlan.
2. Never execute operations.
3. Never generate Python code.
4. Never invent satellite observations, measurements, distances,
   areas, dates, or GIS results.
5. Use ONLY operations from the supplied operation catalog.
6. Operation inputs must reference declared data inputs or previous
   operation IDs.
7. Use deterministic operations whenever possible.
8. Preserve temporal requirements explicitly.
9. Every operation must have a unique ID.
10. The executor performs all actual calculations and data retrieval.
11. Do not invent geographic coordinates.
12. If the user's query does not provide enough information to define
    an AOI, do not fabricate one.
13. Set AOI.resolved to true only when the AOI is explicitly provided
    or otherwise resolved by a trusted geospatial resolution step.
14. If the query names a place but no trusted geocoder has resolved it,
    set AOI.resolved to false.
15. Never provide latitude, longitude, or bounding-box coordinates
    for a place AOI.
16. A place AOI will be resolved by a trusted geographic resolver
    before execution.

AVAILABLE OPERATIONS:
"""


class GeminiQueryPlanner(QueryPlanner):
    """Convert natural-language queries into validated QueryPlans using Gemini."""

    def __init__(
        self,
        registry: OperationRegistry,
        client: genai.Client | None = None,
        model: str = "gemini-3.5-flash-lite",
    ) -> None:
        self.registry = registry
        self.client = client
        self.model = model

    def _get_client(self) -> genai.Client:
        """Create the Gemini client lazily when needed."""
        if self.client is None:
            self.client = genai.Client()
        return self.client

    def _build_prompt(self) -> str:
        """Build the planner prompt from the current operation registry."""
        catalog = self.registry.get_catalog()
        return f"{PLANNER_SYSTEM_PROMPT}\n{catalog}\n"

    @staticmethod
    def _gemini_schema() -> dict[str, Any]:
        """
        Return a Gemini-compatible schema for QueryPlan.

        Gemini Developer API structured output does not accept the
        arbitrary-object schemas generated by Pydantic for fields such
        as dict[str, Any]. Those fields are therefore represented as
        generic JSON objects here and validated by Pydantic afterward.
        """
        return {
            "type": "OBJECT",
            "properties": {
                "plan_id": {
                    "type": "STRING",
                },
                "aoi": {
                    "type": "OBJECT",
                    "properties": {
                        "type": {
                            "type": "STRING",
                            "enum": ["bbox", "polygon", "place"],
                        },
                        "value": {
                            "type": "OBJECT",
                            "properties": {
                                "name": {"type": "STRING"},
                            },
                        },
                        "resolved": {"type": "BOOLEAN"},
                    },
                    "required": ["type", "value", "resolved"],
                },
                "inputs": {
                    "type": "ARRAY",
                    "items": {
                        "type": "OBJECT",
                        "properties": {
                            "id": {"type": "STRING"},
                            "source": {"type": "STRING"},
                            "purpose": {"type": "STRING"},
                            "time_range": {
                                "type": "OBJECT",
                                "properties": {
                                    "start": {"type": "STRING"},
                                    "end": {"type": "STRING"},
                                },
                                "required": ["start", "end"],
                            },
                        },
                        "required": ["id", "source", "purpose"],
                    },
                },
                "operations": {
                    "type": "ARRAY",
                    "items": {
                        "type": "OBJECT",
                        "properties": {
                            "id": {"type": "STRING"},
                            "type": {"type": "STRING"},
                            "inputs": {
                                "type": "ARRAY",
                                "items": {"type": "STRING"},
                            },
                            "parameters": {
                                "type": "OBJECT",
                                "properties": {},
                            },
                        },
                        "required": ["id", "type"],
                    },
                },
                "output": {
                    "type": "OBJECT",
                    "properties": {
                        "type": {
                            "type": "STRING",
                            "enum": [
                                "map",
                                "geojson",
                                "raster",
                                "statistics",
                            ],
                        },
                        "include_geometry": {"type": "BOOLEAN"},
                        "include_statistics": {"type": "BOOLEAN"},
                        "include_evidence": {"type": "BOOLEAN"},
                    },
                    "required": ["type"],
                },
            },
            "required": [
                "plan_id",
                "aoi",
                "inputs",
                "operations",
                "output",
            ],
        }

    def plan(self, query: str) -> QueryPlan:
        """Convert a natural-language query into a structured QueryPlan."""
        if not query.strip():
            raise ValueError("Query must not be empty.")

        client = self._get_client()

        response = client.models.generate_content(
            model=self.model,
            contents=query,
            config=types.GenerateContentConfig(
                system_instruction=self._build_prompt(),
                response_mime_type="application/json",
                response_schema=self._gemini_schema(),
            ),
        )

        if not response.text:
            raise ValueError("Gemini did not return a valid QueryPlan.")

        return QueryPlan.model_validate_json(response.text)